name: healthpod
description: "Private and Secure Storage of Health data in your Solid Pod."
publish_to: "none"
version: 0.1.14+6

environment:
  sdk: ">=3.2.3 <4.0.0"

# To automatically upgrade package dependencies:
#
# `flutter pub upgrade --major-versions`.
#
# To see which dependencies have newer versions available:
#
# `flutter pub outdated`.
#
# (gjw 20250429)

dependencies:
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter

  audioplayers: ^6.2.0
  badges: ^3.1.2
  build_runner: ^2.4.14
  csv: ^6.0.0
  editable: ^2.0.0
  encrypt: ^5.0.3
  file_picker: ^10.1.2
  fl_chart: ^0.71.0
  flutter_inappwebview: ^6.1.5
  flutter_launcher_icons: ^0.14.2
  flutter_markdown: ^0.7.3
  flutter_riverpod: ^2.4.9
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.5.0
  markdown_tooltip: ^0.0.7
  path: ^1.9.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  printing: ^5.11.0
  process_run: ^1.2.2+1
  rdflib: ^0.2.9
  riverpod: ^2.6.1
  shared_preferences: ^2.5.2
  solidpod: ^0.6.6
  syncfusion_flutter_pdf: ^29.1.38
  table_calendar: ^3.0.9
  timeline_tile: ^2.0.0
  universal_io: ^2.2.2
  url_launcher: ^6.3.1
  #version_widget: ^0.0.6
  version_widget:
    git:
      url: https://github.com/anusii/version_widget.git
      ref: main
  webdriver: ^3.0.3
  window_manager: ^0.4.3

dev_dependencies:

  flutter_test:
    sdk: flutter

  import_order_lint:
    git:
      url: https://github.com/anusii/import-order-lint.git
      ref: main

  test: ^1.25.15
  ubuntu_lints: ^0.4.0

dependency_overrides:

  # Why? See https://???? (gjw 20250429)

  flutter_secure_storage_linux: ^2.0.1
  flutter_secure_storage_platform_interface: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/

# Define launcher icons for all platforms (except Linux) so icons for
# the apps can be automatically updated using:
#
# `dart run flutter_launcher_icons`
#
# (gjw 20250429)

flutter_launcher_icons:
  image_path: "assets/images/healthpod_icon.png"
  android: true
  min_sdk_android: 21
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  macos:
    generate: true
  web:
    generate: true
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
