name: healthpod
description: "Secure storage of Health and Medical Records in your Solid Pod."
publish_to: "none"
version: 0.1.1+4

environment:
  sdk: ">=3.2.3 <4.0.0"

# To automatically upgrade package dependencies:
#
# `flutter pub upgrade --major-versions`.
#
# To see which dependencies have newer versions available:
#
# `flutter pub outdated`.


dependencies:
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter

  audioplayers: ^6.2.0
  badges: ^3.1.2
  build_runner: ^2.4.14
  csv: ^6.0.0
  editable: ^2.0.0
  encrypt: ^5.0.3
  file_picker: ^8.1.7
  fl_chart: ^0.70.2
  flutter_inappwebview: ^6.1.5
  flutter_launcher_icons: ^0.14.2
  flutter_markdown: ^0.7.3
  flutter_riverpod: ^2.4.9
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.5.0
  markdown_tooltip: ^0.0.7
  path: ^1.9.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  printing: ^5.14.2
  process_run: ^1.2.2+1
  rdflib: ^0.2.9
  riverpod: ^2.6.1
  shared_preferences: ^2.5.2
  syncfusion_flutter_pdf: ^24.1.41
  table_calendar: ^3.0.9
  timeline_tile: ^2.0.0
  universal_io: ^2.2.2
  url_launcher: ^6.3.1
  webdriver: ^3.0.3
  window_manager: ^0.4.3

  solidpod:
    git:
      url: https://github.com/atangster/solidpod.git
      ref: dev

  version_widget:
    git:
      url: https://github.com/anusii/version_widget.git

dev_dependencies:

  flutter_test:
    sdk: flutter

  import_order_lint:
    git:
      url: https://github.com/anusii/import-order-lint.git
      ref: main

  ubuntu_lints: ^0.4.0
  test: ^1.25.15




dependency_overrides:

  # file: ^7.0.0 # Use only if necessary

  # Add analyzer override to resolve version conflicts
  # analyzer: ^6.6.0

  # TODO 20240710 gjw solid-auth DEPENDS ON intl-0.19.0
  #
  # This may require Anushka's update. We will want to remove this
  # override asap.

  # intl: ^0.19.0
  test_api: ^0.7.3
  flutter_secure_storage_platform_interface: ^1.1.2
  flutter_secure_storage_linux: ^1.2.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/

# Define launcher icons for all platforms (except Linux) so icons for
# the apps can be automatically updated using:
#
# `dart run flutter_launcher_icons`

flutter_launcher_icons:
  image_path: "assets/images/healthpod_icon.png"
  android: true
  min_sdk_android: 21
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  macos:
    generate: true
  web:
    generate: true
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
