name: healthpod
description: "Secure storage of Health and Medical Records in your Solid Pod."
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.2.3 <4.0.0"

# To automatically upgrade package dependencies:
#
# `flutter pub upgrade --major-versions`.
#
# To see which dependencies have newer versions available:
#
# `flutter pub outdated`.

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^8.1.7
  flutter_launcher_icons: ^0.13.1
  flutter_markdown: ^0.7.3
  path: ^1.9.0
  rdflib: ^0.2.9
  solidpod: ^0.6.4
  universal_io: ^2.2.2
  window_manager: ^0.3.9

dev_dependencies:

  dart_code_metrics:
    git:
      url: https://github.com/anusii/dart-code-metrics.git
      ref: dev

  flutter_test:
    sdk: flutter

  ubuntu_lints: ^0.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/healthpod_image.png
    - assets/images/healthpod_logo.png

# Define launcher icons for all platforms (except Linux) so icons for
# the apps can be automatically updated.

flutter_launcher_icons:
  image_path: "assets/images/healthpod_logo.png"
  android: true
  min_sdk_android: 21
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  macos:
    generate: true
  web:
    generate: true
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48