# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from bp_analyser import analyser_pb2 as bp__analyser_dot_analyser__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bp_analyser/analyser_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalyserStub(object):
    """The analyser, as an app sees it.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Analyse = channel.unary_unary(
                '/healthpod.analyser.v1.Analyser/Analyse',
                request_serializer=bp__analyser_dot_analyser__pb2.AnalyseRequest.SerializeToString,
                response_deserializer=bp__analyser_dot_analyser__pb2.AnalyseReply.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/healthpod.analyser.v1.Analyser/Cancel',
                request_serializer=bp__analyser_dot_analyser__pb2.CancelRequest.SerializeToString,
                response_deserializer=bp__analyser_dot_analyser__pb2.CancelReply.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/healthpod.analyser.v1.Analyser/Status',
                request_serializer=bp__analyser_dot_analyser__pb2.StatusRequest.SerializeToString,
                response_deserializer=bp__analyser_dot_analyser__pb2.StatusReply.FromString,
                _registered_method=True)


class AnalyserServicer(object):
    """The analyser, as an app sees it.

    """

    def Analyse(self, request, context):
        """Analyse the caller's readings now, and answer when the result has been
        published back to the caller's Pod.

        Long-running by design: the reply says what happened, so the app needs no
        second call and no polling. A client that stops waiting should cancel the
        call and send Cancel, which are different things — see CancelRequest.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Abandon the analysis running for the caller.

        Answers immediately, whether or not there was anything to stop. The run
        itself stops at its next checkpoint, which is typically within a second.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Whether the analyser is up, and what it is doing.

        Cheap and unauthenticated: it reads no Pod and holds up no analysis, so
        an app can call it before offering to analyse at all.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Analyse': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyse,
                    request_deserializer=bp__analyser_dot_analyser__pb2.AnalyseRequest.FromString,
                    response_serializer=bp__analyser_dot_analyser__pb2.AnalyseReply.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=bp__analyser_dot_analyser__pb2.CancelRequest.FromString,
                    response_serializer=bp__analyser_dot_analyser__pb2.CancelReply.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=bp__analyser_dot_analyser__pb2.StatusRequest.FromString,
                    response_serializer=bp__analyser_dot_analyser__pb2.StatusReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'healthpod.analyser.v1.Analyser', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('healthpod.analyser.v1.Analyser', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Analyser(object):
    """The analyser, as an app sees it.

    """

    @staticmethod
    def Analyse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/healthpod.analyser.v1.Analyser/Analyse',
            bp__analyser_dot_analyser__pb2.AnalyseRequest.SerializeToString,
            bp__analyser_dot_analyser__pb2.AnalyseReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/healthpod.analyser.v1.Analyser/Cancel',
            bp__analyser_dot_analyser__pb2.CancelRequest.SerializeToString,
            bp__analyser_dot_analyser__pb2.CancelReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/healthpod.analyser.v1.Analyser/Status',
            bp__analyser_dot_analyser__pb2.StatusRequest.SerializeToString,
            bp__analyser_dot_analyser__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
